# Generated by Django 2.2.3 on 2019-11-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('admin', 'Administrador OxiLab'), ('artista', 'Artista OxiLab'))},
        ),
    ]
